version: 2.1

jobs:
  build:
    working_directory: /go/src/github.com/hashicorp/nomad
    docker:
      - image: circleci/golang:1.12
        user: root
    environment:
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: make bootstrap
      # - run:
      #     name: Tests
      #     command: make test
      - run:
          name: Compile
          command: make bin
      - persist_to_workspace:
          root: .
          paths:
            - pkg

      # TODO
      # push to s3

  build-container:
    working_directory: /go/src/github.com/hashicorp/nomad
    docker:
      - image: circleci/golang:1.12
        user: root
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ./package
      - run:
          name: Build & publish a container
          command: |
            apt-get update && apt-get install tree
            cd docker
            export TAG="0.5.6-${CIRCLE_BUILD_NUM}-${CIRCLE_BRANCH}"
            echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USER --password-stdin
            make publish

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - build-container:
          context: org-global
          requires:
            - build
