version: 2.1

orbs:
  s3: circleci/aws-s3@1.0.8

jobs:
  compile:
    working_directory: /go/src/github.com/hashicorp/nomad
    docker:
      - image: circleci/golang:1.12
        user: root
    environment:
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: make bootstrap
      # TODO should these pass?
      # - run:
      #     name: Tests
      #     command: make test
      - run:
          name: Compile
          command: |
            apt-get update && apt-get install tree
            make bin
      # TODO credentials?
      # TODO version?
      # - s3/copy:
      #     from: pkg/linux_amd64/nomad
      #     to: 's3://circle-downloads/nomad-'
      - persist_to_workspace:
          root: .
          paths:
            - pkg

  build-container:
    working_directory: /go/src/github.com/hashicorp/nomad
    docker:
      - image: circleci/golang:1.12
        user: root
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: docker
      - run:
          name: Build & publish a container
          command: |
            apt-get update && apt-get install tree
            cd docker
            export TAG="0.5.6-${CIRCLE_BUILD_NUM}-${CIRCLE_BRANCH}"
            echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USER --password-stdin
            make publish
      # TODO vulnerability check

workflows:
  version: 2
  compile-and-package:
    jobs:
      - compile
      - build-container:
          context: org-global
          requires:
            - compile
