version: 2
jobs:
  build:
    working_directory: /go/src/github.com/hashicorp/nomad
    docker:
      - image: circleci/golang:1.12
        user: root
    environment:
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: make bootstrap
      # - run:
      #     name: Tests
      #     command: make test
      - run:
          name: Compile
          command: make bin

      # TODO
      # push to s3

  build_container:
    working_directory: /go/src/github.com/hashicorp/nomad/docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name:
          command: |
            export TAG="0.5.6-${CIRCLE_BUILD_NUM}-${CIRCLE_BRANCH}"
            make publish

# TODO
# cache depedencies

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build_container
