version: 2.1

orbs:
  twistlock: twistlock/twistcli-scan@1.0.4
  s3: circleci/aws-s3@1.0.8

export-image-tag: &export-image-tag
  name: Export image tag
  command: |
    echo 'export TAG="0.5.6-${CIRCLE_BUILD_NUM}-${CIRCLE_BRANCH}"' >> $BASH_ENV

jobs:
  compile:
    working_directory: /go/src/github.com/hashicorp/nomad
    docker:
      - image: circleci/golang:1.12
        user: root
    environment:
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: make bootstrap
      # TODO should these pass?
      # - run:
      #     name: Tests
      #     command: make test
      - run:
          <<: *export-image-tag
      - run:
          name: Compile
          command: |
            apt-get update && apt-get install tree
            make bin
            zip nomad_${TAG}.linux_amd64.zip pkg/linux_amd64/nomad
      # - s3/copy:
      #     from: pkg/linux_amd64/nomad
      #     to: 's3://circle-downloads'
      #     aws-access-key-id: DEV_AWS_ACCESS_KEY_ID
      #     aws-secret-access-key: DEV_AWS_SECRET_ACCESS_KEY
      - persist_to_workspace:
          root: .
          paths:
            - pkg

  publish-cloud-container:
    working_directory: /root/nomad
    docker:
      - image: circleci/command-convenience:0.1.793-476a3ab
        environment:
          NAME: nomad
          DOCKER_REGISTRY: dockerhub
          DOCKERFILE_PATH: docker/Dockerfile
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /root/nomad/docker
      - run: publish

    # TODO server container

workflows:
  version: 2
  compile-and-package:
    jobs:
      - compile:
          context: org-global
      - publish-cloud-container:
          context: org-global
          requires:
            - compile
