version: 2
jobs:
  build:
    working_directory: /go/src/github.com/hashicorp/nomad
    docker:
      - image: circleci/golang:1.12
    environment:
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: make bootstrap
      - run:
          name: Tests
          command: make test
      - run:
          name: Compile
          command: make bin

# TODO
# build container
# publish container
# cache depedencies

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
